name: Notify Slack on Needs Testing Label

on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]

jobs:
  notify:
    if: ${{ github.event.label.name == 'needs-sth' }}
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": "**Needs Testing**: ${{ github.event_name == 'issues' && github.event.issue.title || github.event.pull_request.title }} in ${{ github.repository }}.\n**Link**: ${{ github.event_name == 'issues' && github.event.issue.html_url || github.event.pull_request.html_url }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
