name: Notify Slack on Needs Testing Label V2

on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]

jobs:
  notify:
    if: ${{ github.event.label.name == 'needs-sth' }}
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Send custom HTTP request
        run: |
          curl -X POST -H "Content-Type: application/json" -d '
          {
            "url": "${{ github.event_name == 'issues' && github.event.issue.html_url || github.event.pull_request.html_url }}",
            "type": "${{ github.event_name }}",
            "title": ${{ toJSON(github.event_name == 'issues' && github.event.issue.title || github.event.pull_request.title) }}
          }
          ' ${{ secrets.SLACK_WEBHOOK_URL_V2 }}